services:
  api:
    build: .
    command: gunicorn
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: always

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
