services:
  api:
    build: .
    command: runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    restart: unless-stopped

volumes:
  postgres_data_dev:
