[project]
name = "taskforce"
version = "0.1.0"
description = "Taskforce HQ | Your intelligent AI-powered task management HQ."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "python-decouple>=3.8",
]
