# Generated by Django 5.2 on 2025-05-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_github_id_user_google_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="github_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
    ]
